/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppSideBar: typeof import('./src/components/AppSideBar.vue')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    Calendario: typeof import('./src/components/Calendario.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabAlunos: typeof import('./src/components/TabAlunos.vue')['default']
    TelaLogin: typeof import('./src/components/TelaLogin.vue')['default']
    Temas: typeof import('./src/components/Temas.vue')['default']
    Teste: typeof import('./src/components/Teste.vue')['default']
  }
}
